Add item requests
vnnazaren/java-shareit pull request #3
Opened 2024-05-02 02:24 UTC by vnnazaren

2024-05-02 20:21 UTC, z8q requested changes

2024-05-02 20:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        PageRequest page = PageRequest.of(from > 0 ? from / size : 0, size,
0 делить на число допустимо, а число делить на 0 нельзя. Следующий запрос приведет к ошибке, если еще предварительно создадим пользователя

```
curl --request GET \
  --url 'http://localhost:8080/bookings?from=1&size=0' \
  --header 'X-Sharer-User-Id: 1'
```

2024-05-02 20:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDtoResponse readItemRequest(Long userId, Long requestId) {
В контроллерах принимаем примитивы long, в методах используем обертки Long.
Можно в контроллерах тоже принимать обертки. Для этого метода используются аргументы с аннотациями `@RequestHeader` и `@PathVariable` у них параметр required по дефолту выставлен в true. null не пройдет

2024-05-02 20:21 UTC, z8q commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +package ru.practicum.shareit.item;
По тз еще просят тесты для слоя репозиториев с использованием аннотации `@DataJpaTest`

2024-05-02 20:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      @Validated(Marker.OnUpdate.class)
Для patch в item-controller тоже применимо

2024-05-02 20:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        PageRequest page = PageRequest.of(from > 0 ? from / size : 0, size,
в нескольких местах встречается такая же ошибка

2024-05-02 20:21 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                     @Valid @RequestParam(defaultValue = "10") @Min(0) int size) {
В других контроллерах, в методах с пагинацией тоже встречается

2024-05-02 21:53 UTC, vnnazaren commented on pom.xml
> +			<artifactId>junit-jupiter-params</artifactId>
В интернете подсказали.
Собирался сделать параметризованные тесты для BookingService - там где много разных статусов передаётся, но потом понял что слишком много времени нужно. Быстро не осилю.

2024-05-02 22:38 UTC, vnnazaren commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDtoResponse readItemRequest(Long userId, Long requestId) {
То есть в DTO которые приходят от контроллеров должны быть примитивы?

2024-05-03 21:02 UTC, vnnazaren commented on pom.xml
> +			<artifactId>junit-jupiter-params</artifactId>
Убрал.

2024-05-03 21:04 UTC, vnnazaren commented on src/main/java/ru/practicum/shareit/user/UserController.java
>      @Validated(Marker.OnUpdate.class)
В UserDto поправил.
В Item - всё перепроверил - там на update валидация не нужна.
Всё поправил. Тесты проходит: внутренние и Постман.

2024-05-03 21:05 UTC, vnnazaren commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +                    "Ошибка при добавлении пользователя с ID %s", userDto.getId()
Исправил.

2024-05-03 21:06 UTC, vnnazaren commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                     @Valid @RequestParam(defaultValue = "10") @Min(0) int size) {
Убрал.

2024-05-03 21:07 UTC, vnnazaren commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        PageRequest page = PageRequest.of(from > 0 ? from / size : 0, size,
Исправил. Добавил проверку size.

2024-05-03 21:07 UTC, vnnazaren commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDtoResponse readItemRequest(Long userId, Long requestId) {
Обсудили в пачке.

2024-05-03 21:10 UTC, vnnazaren commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +package ru.practicum.shareit.item;
Добавил тесты репозиториев в которых используется аннотация @Query 
(в интернете говорят их надо тестировать, а стандартные не обязательно).

2024-05-04 19:20 UTC, z8q approved these changes

2024-05-04 20:50 UTC, merged